# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TMDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TMDB

  #UI
  pod 'PKHUD', '~> 5.0'
  pod 'Kingfisher', '5.11.0' , :inhibit_warnings => true

end
